import type {Metadata} from "next";
import {Plus_Jakarta_Sans, JetBrains_Mono} from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Header from "@/components/header";

const plusJakartaSans = Plus_Jakarta_Sans({
    variable: "--font-jakarta-sans",
    subsets: ["latin"],
});

const jetBrainsMono = JetBrains_Mono({
    variable: "--font-jetbrains-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${plusJakartaSans.variable} ${jetBrainsMono.variable} antialiased`}>
        <Header/>
        <main className={"container mx-auto my-10"}>{children}</main>
        <Footer/>
        </body>
        </html>
    );
}
